version: "3"

services:
  server:
    image: nginx:1.24
#    command: sh -c "yum install firewalld; firewall-cmd --permanent --add-service={http,https} ; firewal-cmd --reload"
    volumes: 
      - ./front/my-app/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  back:
    build: ./backend/
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
  front: 
    build: ./front/my-app/
    ports:
      - 5137:5137
#    command: sh -c "apt -y install firewalld; firewall-cmd --permanent --add-service={http,https} ; firewall-cmd --reload"
      
